apply from: "$rootDir/common-android.gradle"

dependencies {
    implementation(project(":app:shared:network"))
    implementation(project(":app:shared:storage"))
    implementation(libs.ktor.core)

    testImplementation(project(":app:shared:network:test"))
    androidTestImplementation(project(":app:shared:network:test"))

    testImplementation(libs.coroutines.test)
    testImplementation(libs.mockk.android)
}
